import pool from './config/database.js';

async function seed() {
  try {
    const businessId = 5;
    console.log(`Seeding analytics data for business ${businessId}...`);

    // 1. Get staff
    const [staff] = await pool.query(`SELECT u.id, u.first_name FROM user u JOIN user_business ub ON u.id = ub.user_id WHERE ub.business_id = ?`, [businessId]);
    if (staff.length === 0) {
        console.log('No staff found for business 5, falling back to any latest business...');
        const [businesses] = await pool.query('SELECT DISTINCT business_id FROM user_business ORDER BY business_id DESC LIMIT 1');
        if (businesses.length) {
            return seedWithId(businesses[0].business_id);
        }
        throw new Error('No businesses with staff available for seeding.');
    }
    
    await seedWithId(businessId);
    
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

async function seedWithId(businessId) {
    const [staff] = await pool.query(`SELECT u.id, u.first_name FROM user u JOIN user_business ub ON u.id = ub.user_id WHERE ub.business_id = ?`, [businessId]);
    
    // 2. Get services
    let [services] = await pool.query(`SELECT id, duration_minutes, price FROM services WHERE business_id = ?`, [businessId]);
    if (services.length === 0) {
      console.log('No services found. Creating dummy services...');
      await pool.query('INSERT INTO services (business_id, name, description, duration_minutes, price) VALUES (?, ?, ?, ?, ?)', [businessId, 'Premium Haircut', 'Test dummy', 45, 25.00]);
      await pool.query('INSERT INTO services (business_id, name, description, duration_minutes, price) VALUES (?, ?, ?, ?, ?)', [businessId, 'Beard Trim', 'Test dummy', 30, 15.00]);
      await pool.query('INSERT INTO services (business_id, name, description, duration_minutes, price) VALUES (?, ?, ?, ?, ?)', [businessId, 'Full Spa Package', 'Test dummy', 120, 150.00]);
      [services] = await pool.query(`SELECT id, duration_minutes, price FROM services WHERE business_id = ?`, [businessId]);
    }

    // 3. Create or get clients
    const [existingClients] = await pool.query(`SELECT id FROM clients WHERE business_id = ?`, [businessId]);
    let clients = existingClients.map(c => c.id);
    
    if (clients.length < 20) {
      console.log('Generating dummy clients...');
      for (let i = 1; i <= 20; i++) {
        const [res] = await pool.query(
          `INSERT INTO clients (business_id, name, phone, email, notes) VALUES (?, ?, ?, ?, ?)`,
          [businessId, `Test Client ${i}`, `+38599${Math.floor(1000000 + Math.random()*9000000)}`, `client${i}@example.com`, `Autogenerated from seed script`]
        );
        clients.push(res.insertId);
      }
    }

    console.log(`Using business ${businessId} with ${clients.length} clients, ${services.length} services, ${staff.length} staff.`);

    const appointments = [];
    const now = new Date();
    
    // Spread ~300 appointments over the last 180 days
    const statuses = ['completed', 'completed', 'completed', 'completed', 'completed', 'cancelled', 'no_show', 'completed', 'completed'];

    for (let i = 0; i < 300; i++) {
        const daysAgo = Math.floor(Math.random() * 180);
        const hour = 9 + Math.floor(Math.random() * 9);
        const minute = (Math.random() > 0.5) ? '00' : '30';
        
        const d = new Date();
        d.setDate(now.getDate() - daysAgo);
        d.setHours(hour, parseInt(minute), 0, 0);

        // Skip sundays 
        if (d.getDay() === 0) continue;

        const clientId = clients[Math.floor(Math.random() * clients.length)];
        const service = services[Math.floor(Math.random() * services.length)];
        const staffId = staff[Math.floor(Math.random() * staff.length)].id;
        const status = statuses[Math.floor(Math.random() * statuses.length)];

        const datetimeStr = d.toISOString().slice(0, 19).replace('T', ' ');

        appointments.push([
            businessId,
            clientId,
            service.id,
            staffId,
            datetimeStr,
            staffId, // user_id (actor)
            status
        ]);
    }

    console.log(`Inserting ${appointments.length} appointments...`);
    
    for (const appt of appointments) {
        await pool.query(`
            INSERT INTO appointment (business_id, client_id, service_id, assigned_to_user_id, appointment_datetime, user_id, status)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        `, appt);
    }

    console.log('Seeding completed successfully! Check the Analytics page in the browser.');
    process.exit(0);
}

seed();
