ALTER TABLE business
ADD COLUMN sms_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN send_confirmation BOOLEAN DEFAULT TRUE,
ADD COLUMN send_reminder BOOLEAN DEFAULT TRUE,
ADD COLUMN send_cancellation BOOLEAN DEFAULT TRUE;
